-- Adiciona colunas de vínculo à tabela AD_ADLEADSATIVIDADES
ALTER TABLE AD_ADLEADSATIVIDADES ADD CODPARC NUMBER;
ALTER TABLE AD_ADLEADSATIVIDADES ADD CODROTA NUMBER;
ALTER TABLE AD_ADLEADSATIVIDADES ADD CODVISITA NUMBER;

-- Comentários para documentação
COMMENT ON COLUMN AD_ADLEADSATIVIDADES.CODPARC IS 'Código do Parceiro vinculado (Sankhya)';
COMMENT ON COLUMN AD_ADLEADSATIVIDADES.CODROTA IS 'Código da Rota vinculada';
COMMENT ON COLUMN AD_ADLEADSATIVIDADES.CODVISITA IS 'Código da Visita vinculada';
