
-- Tabela para armazenar logs de sincronização offline
CREATE TABLE AD_LOGS_SINCRONIZACAO (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_EMPRESA NUMBER NOT NULL,
  CODUSUARIO NUMBER NOT NULL,
  NOME_USUARIO VARCHAR2(200),
  TIPO_OPERACAO VARCHAR2(50) NOT NULL,
  STATUS VARCHAR2(20) NOT NULL,
  DADOS_ENVIADOS CLOB,
  RESPOSTA CLOB,
  ERRO CLOB,
  DATA_HORA TIMESTAMP DEFAULT SYSTIMESTAMP,
  NUMERO_DOCUMENTO VARCHAR2(50),
  CONSTRAINT CHK_SYNC_STATUS CHECK (STATUS IN ('SUCESSO', 'ERRO', 'PENDENTE')),
  CONSTRAINT CHK_SYNC_TIPO CHECK (TIPO_OPERACAO IN ('PEDIDO', 'PARCEIRO', 'PRODUTO'))
);

-- Índices para otimização
CREATE INDEX IDX_LOGS_SYNC_EMPRESA ON AD_LOGS_SINCRONIZACAO(ID_EMPRESA);
CREATE INDEX IDX_LOGS_SYNC_DATA ON AD_LOGS_SINCRONIZACAO(DATA_HORA);
CREATE INDEX IDX_LOGS_SYNC_STATUS ON AD_LOGS_SINCRONIZACAO(STATUS);
CREATE INDEX IDX_LOGS_SYNC_USUARIO ON AD_LOGS_SINCRONIZACAO(CODUSUARIO);

-- Comentários
COMMENT ON TABLE AD_LOGS_SINCRONIZACAO IS 'Registros de sincronização de dados offline para online';
COMMENT ON COLUMN AD_LOGS_SINCRONIZACAO.TIPO_OPERACAO IS 'Tipo de operação: PEDIDO, PARCEIRO, PRODUTO';
COMMENT ON COLUMN AD_LOGS_SINCRONIZACAO.STATUS IS 'Status: SUCESSO, ERRO, PENDENTE';
