
-- =====================================================
-- SCRIPT DE CRIAÇÃO DAS TABELAS DE FUNIS NO ORACLE
-- =====================================================

-- 1. Tabela de Funis
CREATE TABLE AD_FUNIS (
    CODFUNIL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_EMPRESA NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(500),
    COR VARCHAR2(20) DEFAULT '#3b82f6',
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    DATA_CRIACAO DATE DEFAULT SYSDATE,
    DATA_ATUALIZACAO DATE DEFAULT SYSDATE
);

-- Índices para performance
CREATE INDEX IDX_FUNIS_EMPRESA ON AD_FUNIS(ID_EMPRESA, ATIVO);
CREATE INDEX IDX_FUNIS_ATIVO ON AD_FUNIS(ATIVO);

-- 2. Tabela de Estágios dos Funis
CREATE TABLE AD_FUNISESTAGIOS (
    CODESTAGIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODFUNIL NUMBER NOT NULL,
    ID_EMPRESA NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    ORDEM NUMBER NOT NULL,
    COR VARCHAR2(20) DEFAULT '#3b82f6',
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    DATA_CRIACAO DATE DEFAULT SYSDATE,
    DATA_ATUALIZACAO DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ESTAGIOS_FUNIL FOREIGN KEY (CODFUNIL) REFERENCES AD_FUNIS(CODFUNIL)
);

-- Índices para performance
CREATE INDEX IDX_ESTAGIOS_FUNIL ON AD_FUNISESTAGIOS(CODFUNIL, ATIVO);
CREATE INDEX IDX_ESTAGIOS_EMPRESA ON AD_FUNISESTAGIOS(ID_EMPRESA, ATIVO);
CREATE INDEX IDX_ESTAGIOS_ORDEM ON AD_FUNISESTAGIOS(CODFUNIL, ORDEM);

-- 3. Tabela de Permissões de Funis por Usuário
CREATE TABLE AD_FUNISUSUARIOS (
    CODFUNILUSUARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODFUNIL NUMBER NOT NULL,
    CODUSUARIO NUMBER NOT NULL,
    ID_EMPRESA NUMBER NOT NULL,
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    DATA_CRIACAO DATE DEFAULT SYSDATE,
    CONSTRAINT FK_FUNISUSUARIOS_FUNIL FOREIGN KEY (CODFUNIL) REFERENCES AD_FUNIS(CODFUNIL),
    CONSTRAINT UK_FUNISUSUARIO UNIQUE (CODFUNIL, CODUSUARIO, ID_EMPRESA)
);

-- Índices para performance
CREATE INDEX IDX_FUNISUSUARIOS_USUARIO ON AD_FUNISUSUARIOS(CODUSUARIO, ATIVO);
CREATE INDEX IDX_FUNISUSUARIOS_EMPRESA ON AD_FUNISUSUARIOS(ID_EMPRESA, ATIVO);

-- 4. Tabela de Leads
CREATE TABLE AD_LEADS (
    CODLEAD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_EMPRESA NUMBER NOT NULL,
    NOME VARCHAR2(200) NOT NULL,
    DESCRICAO VARCHAR2(1000),
    VALOR NUMBER(15,2) DEFAULT 0,
    CODESTAGIO NUMBER,
    CODFUNIL NUMBER,
    DATA_VENCIMENTO DATE,
    TIPO_TAG VARCHAR2(50),
    COR_TAG VARCHAR2(20) DEFAULT '#3b82f6',
    CODPARC NUMBER,
    CODUSUARIO NUMBER,
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    STATUS_LEAD VARCHAR2(20) DEFAULT 'EM_ANDAMENTO' CHECK (STATUS_LEAD IN ('EM_ANDAMENTO', 'GANHO', 'PERDIDO')),
    MOTIVO_PERDA VARCHAR2(500),
    DATA_CRIACAO DATE DEFAULT SYSDATE,
    DATA_ATUALIZACAO DATE DEFAULT SYSDATE,
    DATA_CONCLUSAO DATE,
    CONSTRAINT FK_LEADS_ESTAGIO FOREIGN KEY (CODESTAGIO) REFERENCES AD_FUNISESTAGIOS(CODESTAGIO),
    CONSTRAINT FK_LEADS_FUNIL FOREIGN KEY (CODFUNIL) REFERENCES AD_FUNIS(CODFUNIL)
);

-- Índices para performance
CREATE INDEX IDX_LEADS_EMPRESA ON AD_LEADS(ID_EMPRESA, ATIVO);
CREATE INDEX IDX_LEADS_ESTAGIO ON AD_LEADS(CODESTAGIO, ATIVO);
CREATE INDEX IDX_LEADS_FUNIL ON AD_LEADS(CODFUNIL, ATIVO);
CREATE INDEX IDX_LEADS_USUARIO ON AD_LEADS(CODUSUARIO, ATIVO);
CREATE INDEX IDX_LEADS_STATUS ON AD_LEADS(STATUS_LEAD, ATIVO);
CREATE INDEX IDX_LEADS_VENCIMENTO ON AD_LEADS(DATA_VENCIMENTO);

-- 5. Tabela de Atividades dos Leads
CREATE TABLE AD_ADLEADSATIVIDADES (
    CODATIVIDADE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODLEAD NUMBER,
    ID_EMPRESA NUMBER NOT NULL,
    TIPO VARCHAR2(20) NOT NULL CHECK (TIPO IN ('LIGACAO', 'EMAIL', 'REUNIAO', 'VISITA', 'PEDIDO', 'CLIENTE', 'NOTA', 'WHATSAPP', 'PROPOSTA')),
    DESCRICAO VARCHAR2(1000),
    DATA_HORA TIMESTAMP DEFAULT SYSTIMESTAMP,
    DATA_INICIO TIMESTAMP,
    DATA_FIM TIMESTAMP,
    CODUSUARIO NUMBER NOT NULL,
    DADOS_COMPLEMENTARES CLOB,
    COR VARCHAR2(20),
    ORDEM NUMBER DEFAULT 0,
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    STATUS VARCHAR2(20) DEFAULT 'AGUARDANDO' CHECK (STATUS IN ('AGUARDANDO', 'ATRASADO', 'REALIZADO')),
    DATA_CRIACAO DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ATIVIDADES_LEAD FOREIGN KEY (CODLEAD) REFERENCES AD_LEADS(CODLEAD)
);

-- Índices para performance
CREATE INDEX IDX_ATIVIDADES_LEAD ON AD_ADLEADSATIVIDADES(CODLEAD, ATIVO);
CREATE INDEX IDX_ATIVIDADES_EMPRESA ON AD_ADLEADSATIVIDADES(ID_EMPRESA, ATIVO);
CREATE INDEX IDX_ATIVIDADES_USUARIO ON AD_ADLEADSATIVIDADES(CODUSUARIO, ATIVO);
CREATE INDEX IDX_ATIVIDADES_DATA ON AD_ADLEADSATIVIDADES(DATA_INICIO);
CREATE INDEX IDX_ATIVIDADES_STATUS ON AD_ADLEADSATIVIDADES(STATUS, ATIVO);

-- 6. Tabela de Produtos dos Leads
CREATE TABLE AD_ADLEADSPRODUTOS (
    CODITEM NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODLEAD NUMBER NOT NULL,
    ID_EMPRESA NUMBER NOT NULL,
    CODPROD NUMBER NOT NULL,
    DESCRPROD VARCHAR2(200) NOT NULL,
    QUANTIDADE NUMBER(15,3) NOT NULL,
    VLRUNIT NUMBER(15,2) NOT NULL,
    VLRTOTAL NUMBER(15,2) NOT NULL,
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    DATA_INCLUSAO DATE DEFAULT SYSDATE,
    CONSTRAINT FK_LEADSPRODUTOS_LEAD FOREIGN KEY (CODLEAD) REFERENCES AD_LEADS(CODLEAD)
);

-- Índices para performance
CREATE INDEX IDX_LEADSPRODUTOS_LEAD ON AD_ADLEADSPRODUTOS(CODLEAD, ATIVO);
CREATE INDEX IDX_LEADSPRODUTOS_EMPRESA ON AD_ADLEADSPRODUTOS(ID_EMPRESA, ATIVO);
CREATE INDEX IDX_LEADSPRODUTOS_PRODUTO ON AD_ADLEADSPRODUTOS(CODPROD);

-- =====================================================
-- TRIGGERS PARA ATUALIZAÇÃO AUTOMÁTICA DE DATAS
-- =====================================================

-- Trigger para AD_FUNIS
CREATE OR REPLACE TRIGGER TRG_FUNIS_UPDATE
BEFORE UPDATE ON AD_FUNIS
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := SYSDATE;
END;
/

-- Trigger para AD_FUNISESTAGIOS
CREATE OR REPLACE TRIGGER TRG_ESTAGIOS_UPDATE
BEFORE UPDATE ON AD_FUNISESTAGIOS
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := SYSDATE;
END;
/

-- Trigger para AD_LEADS
CREATE OR REPLACE TRIGGER TRG_LEADS_UPDATE
BEFORE UPDATE ON AD_LEADS
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := SYSDATE;
END;
/

-- =====================================================
-- COMENTÁRIOS NAS TABELAS
-- =====================================================

COMMENT ON TABLE AD_FUNIS IS 'Tabela de Funis de Vendas';
COMMENT ON TABLE AD_FUNISESTAGIOS IS 'Tabela de Estágios dos Funis';
COMMENT ON TABLE AD_FUNISUSUARIOS IS 'Tabela de Permissões de Usuários nos Funis';
COMMENT ON TABLE AD_LEADS IS 'Tabela de Leads do Sistema';
COMMENT ON TABLE AD_ADLEADSATIVIDADES IS 'Tabela de Atividades dos Leads';
COMMENT ON TABLE AD_ADLEADSPRODUTOS IS 'Tabela de Produtos dos Leads';

-- =====================================================
-- COMMIT DAS ALTERAÇÕES
-- =====================================================

COMMIT;
