-- Tabela para armazenar clientes com acesso manual por usuário
CREATE TABLE AD_ACESSOS_CLIENTES (
  CODACESSO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CODUSUARIO NUMBER NOT NULL,
  CODPARC NUMBER NOT NULL,
  DTINCLUSAO DATE DEFAULT SYSDATE,
  CONSTRAINT UK_ACESSOS_CLIENTES UNIQUE (CODUSUARIO, CODPARC)
);

-- Índice para busca por usuário
CREATE INDEX IDX_ACESSOS_CLI_USUARIO ON AD_ACESSOS_CLIENTES(CODUSUARIO);

-- Tabela para armazenar produtos com acesso manual por usuário
CREATE TABLE AD_ACESSOS_PRODUTOS (
  CODACESSO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CODUSUARIO NUMBER NOT NULL,
  CODPROD NUMBER NOT NULL,
  DTINCLUSAO DATE DEFAULT SYSDATE,
  CONSTRAINT UK_ACESSOS_PRODUTOS UNIQUE (CODUSUARIO, CODPROD)
);

-- Índice para busca por usuário
CREATE INDEX IDX_ACESSOS_PROD_USUARIO ON AD_ACESSOS_PRODUTOS(CODUSUARIO);

-- Comentários das tabelas
COMMENT ON TABLE AD_ACESSOS_CLIENTES IS 'Clientes com acesso manual por usuário';
COMMENT ON COLUMN AD_ACESSOS_CLIENTES.CODUSUARIO IS 'Código do usuário';
COMMENT ON COLUMN AD_ACESSOS_CLIENTES.CODPARC IS 'Código do parceiro/cliente';
COMMENT ON COLUMN AD_ACESSOS_CLIENTES.DTINCLUSAO IS 'Data de inclusão do acesso';

COMMENT ON TABLE AD_ACESSOS_PRODUTOS IS 'Produtos com acesso manual por usuário';
COMMENT ON COLUMN AD_ACESSOS_PRODUTOS.CODUSUARIO IS 'Código do usuário';
COMMENT ON COLUMN AD_ACESSOS_PRODUTOS.CODPROD IS 'Código do produto';
COMMENT ON COLUMN AD_ACESSOS_PRODUTOS.DTINCLUSAO IS 'Data de inclusão do acesso';
