
-- =====================================================
-- SCRIPT DE CRIAÇÃO DA TABELA DE TIPOS DE PEDIDO
-- =====================================================

-- Tabela de Tipos de Pedido (configuração)
CREATE TABLE AD_TIPOSPEDIDO (
    CODTIPOPEDIDO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_EMPRESA NUMBER NOT NULL,
    CODUSUARIO_CRIADOR NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(500),
    CODTIPOPER NUMBER NOT NULL,
    MODELO_NOTA NUMBER NOT NULL,
    TIPMOV VARCHAR2(1) DEFAULT 'P' CHECK (TIPMOV IN ('P', 'V')),
    CODTIPVENDA NUMBER NOT NULL,
    COR VARCHAR2(20) DEFAULT '#3b82f6',
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    DATA_CRIACAO DATE DEFAULT SYSDATE,
    DATA_ATUALIZACAO DATE DEFAULT SYSDATE,
    CONSTRAINT UK_TIPOPEDIDO_NOME_EMPRESA UNIQUE (NOME, ID_EMPRESA, ATIVO)
);

-- Índices para performance
CREATE INDEX IDX_TIPOSPEDIDO_EMPRESA ON AD_TIPOSPEDIDO(ID_EMPRESA, ATIVO);
CREATE INDEX IDX_TIPOSPEDIDO_USUARIO ON AD_TIPOSPEDIDO(CODUSUARIO_CRIADOR);
CREATE INDEX IDX_TIPOSPEDIDO_ATIVO ON AD_TIPOSPEDIDO(ATIVO);

-- Trigger para atualização automática de data
CREATE OR REPLACE TRIGGER TRG_TIPOSPEDIDO_UPDATE
BEFORE UPDATE ON AD_TIPOSPEDIDO
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := SYSDATE;
END;
/

-- Comentários na tabela
COMMENT ON TABLE AD_TIPOSPEDIDO IS 'Tabela de Configuração de Tipos de Pedido';
COMMENT ON COLUMN AD_TIPOSPEDIDO.CODTIPOPEDIDO IS 'Código único do tipo de pedido';
COMMENT ON COLUMN AD_TIPOSPEDIDO.ID_EMPRESA IS 'ID da empresa proprietária';
COMMENT ON COLUMN AD_TIPOSPEDIDO.CODUSUARIO_CRIADOR IS 'Código do usuário que criou o tipo';
COMMENT ON COLUMN AD_TIPOSPEDIDO.NOME IS 'Nome do tipo de pedido';
COMMENT ON COLUMN AD_TIPOSPEDIDO.DESCRICAO IS 'Descrição detalhada do tipo';
COMMENT ON COLUMN AD_TIPOSPEDIDO.CODTIPOPER IS 'Código do tipo de operação vinculado';
COMMENT ON COLUMN AD_TIPOSPEDIDO.MODELO_NOTA IS 'Número do modelo da nota';
COMMENT ON COLUMN AD_TIPOSPEDIDO.TIPMOV IS 'Tipo de movimento (P=Pedido, V=Venda)';
COMMENT ON COLUMN AD_TIPOSPEDIDO.CODTIPVENDA IS 'Código da condição comercial';
COMMENT ON COLUMN AD_TIPOSPEDIDO.COR IS 'Cor de identificação visual';
COMMENT ON COLUMN AD_TIPOSPEDIDO.ATIVO IS 'Status do tipo de pedido';

-- Commit das alterações
COMMIT;
