
-- Tabela para controle de pedidos da força de vendas
CREATE TABLE AD_PEDIDOS_FDV (
  ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_EMPRESA NUMBER NOT NULL,
  ORIGEM VARCHAR2(20) NOT NULL, -- 'RAPIDO', 'LEAD' ou 'OFFLINE'
  CODLEAD NUMBER, -- Código do lead se origem = 'LEAD'
  CORPO_JSON CLOB NOT NULL,
  STATUS VARCHAR2(20) NOT NULL, -- 'SUCESSO' ou 'ERRO'
  NUNOTA NUMBER, -- Número da nota se sucesso
  ERRO CLOB, -- Mensagem de erro se falhou
  TENTATIVAS NUMBER DEFAULT 1,
  CODUSUARIO NUMBER NOT NULL,
  NOME_USUARIO VARCHAR2(200),
  DATA_CRIACAO TIMESTAMP DEFAULT SYSTIMESTAMP,
  DATA_ULTIMA_TENTATIVA TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT CHK_PEDIDO_FDV_ORIGEM CHECK (ORIGEM IN ('RAPIDO', 'LEAD', 'OFFLINE')),
  CONSTRAINT CHK_PEDIDO_FDV_STATUS CHECK (STATUS IN ('SUCESSO', 'ERRO'))
);

-- Índices para otimização
CREATE INDEX IDX_PEDIDOS_FDV_EMPRESA ON AD_PEDIDOS_FDV(ID_EMPRESA);
CREATE INDEX IDX_PEDIDOS_FDV_STATUS ON AD_PEDIDOS_FDV(STATUS);
CREATE INDEX IDX_PEDIDOS_FDV_ORIGEM ON AD_PEDIDOS_FDV(ORIGEM);
CREATE INDEX IDX_PEDIDOS_FDV_LEAD ON AD_PEDIDOS_FDV(CODLEAD);
CREATE INDEX IDX_PEDIDOS_FDV_USUARIO ON AD_PEDIDOS_FDV(CODUSUARIO);
CREATE INDEX IDX_PEDIDOS_FDV_DATA ON AD_PEDIDOS_FDV(DATA_CRIACAO);

-- Comentários
COMMENT ON TABLE AD_PEDIDOS_FDV IS 'Controle e logs de pedidos da força de vendas';
COMMENT ON COLUMN AD_PEDIDOS_FDV.ORIGEM IS 'Origem: RAPIDO, LEAD ou OFFLINE';
COMMENT ON COLUMN AD_PEDIDOS_FDV.STATUS IS 'Status: SUCESSO ou ERRO';
COMMENT ON COLUMN AD_PEDIDOS_FDV.TENTATIVAS IS 'Quantidade de tentativas de criação';
