
-- =====================================================
-- SCRIPT DE CRIAÇÃO DA TABELA DE CONFIGURAÇÃO DE TABELAS DE PREÇOS
-- =====================================================

-- Tabela de Configuração de Tabelas de Preços (quais aparecem para os vendedores)
CREATE TABLE AD_TABELASPRECOSCONFIG (
    CODCONFIG NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_EMPRESA NUMBER NOT NULL,
    CODUSUARIO_CRIADOR NUMBER NOT NULL,
    NUTAB NUMBER NOT NULL,
    CODTAB VARCHAR2(10) NOT NULL,
    DESCRICAO VARCHAR2(200),
    ATIVO CHAR(1) DEFAULT 'S' CHECK (ATIVO IN ('S', 'N')),
    DATA_CRIACAO DATE DEFAULT SYSDATE,
    DATA_ATUALIZACAO DATE DEFAULT SYSDATE,
    CONSTRAINT UK_TABELAPRECO_CONFIG UNIQUE (NUTAB, ID_EMPRESA, ATIVO)
);

-- Índices para performance
CREATE INDEX IDX_TABELASPRECOSCONFIG_EMPRESA ON AD_TABELASPRECOSCONFIG(ID_EMPRESA, ATIVO);
CREATE INDEX IDX_TABELASPRECOSCONFIG_USUARIO ON AD_TABELASPRECOSCONFIG(CODUSUARIO_CRIADOR);
CREATE INDEX IDX_TABELASPRECOSCONFIG_ATIVO ON AD_TABELASPRECOSCONFIG(ATIVO);
CREATE INDEX IDX_TABELASPRECOSCONFIG_NUTAB ON AD_TABELASPRECOSCONFIG(NUTAB);

-- Trigger para atualização automática de data
CREATE OR REPLACE TRIGGER TRG_TABELASPRECOSCONFIG_UPDATE
BEFORE UPDATE ON AD_TABELASPRECOSCONFIG
FOR EACH ROW
BEGIN
    :NEW.DATA_ATUALIZACAO := SYSDATE;
END;
/

-- Comentários na tabela
COMMENT ON TABLE AD_TABELASPRECOSCONFIG IS 'Tabela de Configuração de Tabelas de Preços disponíveis para vendedores';
COMMENT ON COLUMN AD_TABELASPRECOSCONFIG.CODCONFIG IS 'Código único da configuração';
COMMENT ON COLUMN AD_TABELASPRECOSCONFIG.ID_EMPRESA IS 'ID da empresa proprietária';
COMMENT ON COLUMN AD_TABELASPRECOSCONFIG.CODUSUARIO_CRIADOR IS 'Código do usuário que criou a configuração';
COMMENT ON COLUMN AD_TABELASPRECOSCONFIG.NUTAB IS 'Número da tabela de preços (referência AS_TABELA_PRECOS)';
COMMENT ON COLUMN AD_TABELASPRECOSCONFIG.CODTAB IS 'Código da tabela de preços';
COMMENT ON COLUMN AD_TABELASPRECOSCONFIG.DESCRICAO IS 'Descrição da tabela de preços';
COMMENT ON COLUMN AD_TABELASPRECOSCONFIG.ATIVO IS 'Status da configuração';

-- Commit das alterações
COMMIT;
