--------------------------------------------------------
--  DDL for Table AD_RELATORIOS_MODELOS
--------------------------------------------------------

CREATE TABLE "SYSTEM"."AD_RELATORIOS_MODELOS" 
(	"ID_MODELO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE, 
	"ID_EMPRESA" NUMBER, 
	"CODUSUARIO" NUMBER, 
	"NOME" VARCHAR2(200 BYTE), 
	"DESCRICAO" VARCHAR2(500 BYTE), 
	"ESTRUTURA_JSON" CLOB, 
	"CABEÇALHO_JSON" CLOB, 
	"RODAPE_JSON" CLOB, 
	"LOGO_URL" VARCHAR2(500 BYTE), 
	"ATIVO" CHAR(1 BYTE) DEFAULT 'S', 
	"DATA_CRIACAO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"DATA_ATUALIZACAO" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 TABLESPACE "SYSTEM" 
 LOB ("ESTRUTURA_JSON") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("CABEÇALHO_JSON") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("RODAPE_JSON") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

COMMENT ON COLUMN "SYSTEM"."AD_RELATORIOS_MODELOS"."ESTRUTURA_JSON" IS 'JSON contendo a disposição dos campos arrastados (Drag and Drop)';
COMMENT ON TABLE "SYSTEM"."AD_RELATORIOS_MODELOS"  IS 'Tabela de Modelos de Relatórios Customizados';
