
-- =====================================================
-- SCRIPT PARA VERIFICAR E ADICIONAR COLUNAS DE CONTROLE DE ACESSO
-- =====================================================

-- 1. Verificar e adicionar CODUSUARIO na tabela AD_ADLEADSATIVIDADES (se não existir)
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'AD_ADLEADSATIVIDADES' AND COLUMN_NAME = 'CODUSUARIO';
  
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE AD_ADLEADSATIVIDADES ADD (CODUSUARIO NUMBER)';
    DBMS_OUTPUT.PUT_LINE('✅ Coluna CODUSUARIO adicionada em AD_ADLEADSATIVIDADES');
  ELSE
    DBMS_OUTPUT.PUT_LINE('ℹ️ Coluna CODUSUARIO já existe em AD_ADLEADSATIVIDADES');
  END IF;
END;
/

-- 2. Verificar CODUSUARIO na tabela AD_LEADS
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'AD_LEADS' AND COLUMN_NAME = 'CODUSUARIO';
  
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE AD_LEADS ADD (CODUSUARIO NUMBER)';
    DBMS_OUTPUT.PUT_LINE('✅ Coluna CODUSUARIO adicionada em AD_LEADS');
  ELSE
    DBMS_OUTPUT.PUT_LINE('ℹ️ Coluna CODUSUARIO já existe em AD_LEADS');
  END IF;
END;
/

-- 3. Verificar CODVEND na tabela AS_PARCEIROS
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'AS_PARCEIROS' AND COLUMN_NAME = 'CODVEND';
  
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE AS_PARCEIROS ADD (CODVEND NUMBER)';
    DBMS_OUTPUT.PUT_LINE('✅ Coluna CODVEND adicionada em AS_PARCEIROS');
  ELSE
    DBMS_OUTPUT.PUT_LINE('ℹ️ Coluna CODVEND já existe em AS_PARCEIROS');
  END IF;
END;
/

-- 4. Verificar CODVEND na tabela AS_CABECALHO_NOTA
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'AS_CABECALHO_NOTA' AND COLUMN_NAME = 'CODVEND';
  
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE AS_CABECALHO_NOTA ADD (CODVEND NUMBER)';
    DBMS_OUTPUT.PUT_LINE('✅ Coluna CODVEND adicionada em AS_CABECALHO_NOTA');
  ELSE
    DBMS_OUTPUT.PUT_LINE('ℹ️ Coluna CODVEND já existe em AS_CABECALHO_NOTA');
  END IF;
END;
/

-- 5. Verificar CODVEND na tabela AD_USUARIOSVENDAS
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'AD_USUARIOSVENDAS' AND COLUMN_NAME = 'CODVEND';
  
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE AD_USUARIOSVENDAS ADD (CODVEND NUMBER)';
    DBMS_OUTPUT.PUT_LINE('✅ Coluna CODVEND adicionada em AD_USUARIOSVENDAS');
  ELSE
    DBMS_OUTPUT.PUT_LINE('ℹ️ Coluna CODVEND já existe em AD_USUARIOSVENDAS');
  END IF;
END;
/

-- 6. Verificar CODGER e TIPVEND na tabela AS_VENDEDORES
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'AS_VENDEDORES' AND COLUMN_NAME = 'CODGER';
  
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE AS_VENDEDORES ADD (CODGER NUMBER)';
    DBMS_OUTPUT.PUT_LINE('✅ Coluna CODGER adicionada em AS_VENDEDORES');
  ELSE
    DBMS_OUTPUT.PUT_LINE('ℹ️ Coluna CODGER já existe em AS_VENDEDORES');
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'AS_VENDEDORES' AND COLUMN_NAME = 'TIPVEND';
  
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE AS_VENDEDORES ADD (TIPVEND VARCHAR2(1) DEFAULT ''V'' CHECK (TIPVEND IN (''V'', ''G'')))';
    DBMS_OUTPUT.PUT_LINE('✅ Coluna TIPVEND adicionada em AS_VENDEDORES');
  ELSE
    DBMS_OUTPUT.PUT_LINE('ℹ️ Coluna TIPVEND já existe em AS_VENDEDORES');
  END IF;
END;
/

-- 7. Criar índices para performance
CREATE INDEX IF NOT EXISTS IDX_PARCEIROS_VENDEDOR ON AS_PARCEIROS(CODVEND, ID_SISTEMA, SANKHYA_ATUAL, ATIVO);
CREATE INDEX IF NOT EXISTS IDX_LEADS_USUARIO ON AD_LEADS(CODUSUARIO, ID_EMPRESA, ATIVO);
CREATE INDEX IF NOT EXISTS IDX_ATIVIDADES_USUARIO ON AD_ADLEADSATIVIDADES(CODUSUARIO, ID_EMPRESA, ATIVO);
CREATE INDEX IF NOT EXISTS IDX_PEDIDOS_VENDEDOR ON AS_CABECALHO_NOTA(CODVEND, ID_SISTEMA, SANKHYA_ATUAL);
CREATE INDEX IF NOT EXISTS IDX_VENDEDORES_GERENTE ON AS_VENDEDORES(CODGER, ID_SISTEMA, SANKHYA_ATUAL, ATIVO);
CREATE INDEX IF NOT EXISTS IDX_USUARIOS_VENDEDOR ON AD_USUARIOSVENDAS(CODVEND, ID_EMPRESA);

COMMIT;

DBMS_OUTPUT.PUT_LINE('✅ Verificação completa. Todas as colunas necessárias estão disponíveis.');
