-- SQL para criação da tabela de Políticas Comerciais no Oracle
-- Usar este script para criar a estrutura necessária para o novo recurso.

CREATE TABLE AD_POLITICASCOMERCIAIS (
    ID_POLITICA NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_EMPRESA NUMBER NOT NULL,
    NOME_POLITICA VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(500),
    ATIVO CHAR(1) DEFAULT 'S' NOT NULL,
    DATA_CRIACAO DATE DEFAULT SYSDATE,
    DATA_ATUALIZACAO DATE,
    PRIORIDADE NUMBER DEFAULT 0,

    -- Escopo Organizacional
    ESCOPO_REGIOES VARCHAR2(1000), -- IDs das regiões, separados por vírgula
    ESCOPO_ESTADOS VARCHAR2(1000), -- UFs, separadas por vírgula (ex: 'SP,RJ,MG')
    ESCOPO_CIDADES VARCHAR2(4000), -- Códigos das cidades (CODCID), separados por vírgula
    ESCOPO_ROTAS VARCHAR2(4000),   -- Códigos das rotas (CODROTA), separados por vírgula

    -- Segmentação de Cliente
    SEG_PERFIS_CLIENTE VARCHAR2(1000),  -- IDs dos perfis, separados por vírgula
    SEG_VENDEDORES VARCHAR2(4000),      -- Códigos dos vendedores (CODVEND), separados por vírgula
    SEG_EQUIPES VARCHAR2(1000),         -- IDs das equipes, separados por vírgula
    SEG_CLIENTES_MANUAL CLOB,           -- Códigos dos parceiros (CODPARC), separados por vírgula

    -- Condições da Transação
    COND_COMERCIAIS VARCHAR2(1000),    -- IDs das condições comerciais, separados por vírgula
    COND_TIPOS_TITULO VARCHAR2(1000),  -- IDs dos tipos de título, separados por vírgula

    -- Produtos
    PROD_MARCAS VARCHAR2(1000),         -- IDs das marcas, separados por vírgula
    PROD_FAMILIAS VARCHAR2(1000),       -- IDs das famílias/grupos de produtos, separados por vírgula
    PROD_PRODUTOS_MANUAL CLOB,          -- Códigos dos produtos (CODPROD), separados por vírgula

    -- Resultado da Regra
    RESULT_NUTAB NUMBER,               -- FK para a tabela de preços (AS_TABELA_PRECOS.NUTAB)
    RESULT_PERCDESCONTO_MAX NUMBER(5, 2),
    RESULT_PERCACIMA_MAX NUMBER(5, 2),

    CONSTRAINT PK_AD_POLITICASCOMERCIAIS PRIMARY KEY (ID_POLITICA)
);

COMMENT ON TABLE AD_POLITICASCOMERCIAIS IS 'Tabela para armazenar as políticas comerciais e suas regras.';
COMMENT ON COLUMN AD_POLITICASCOMERCIAIS.ID_EMPRESA IS 'Identificador da empresa à qual a política pertence.';
COMMENT ON COLUMN AD_POLITICASCOMERCIAIS.NOME_POLITICA IS 'Nome descritivo da política comercial.';
COMMENT ON COLUMN AD_POLITICASCOMERCIAIS.ATIVO IS 'Status da política (S - Ativa, N - Inativa).';
COMMENT ON COLUMN AD_POLITICASCOMERCIAIS.PRIORIDADE IS 'Ordem de aplicação da política. Menor número = maior prioridade.';
COMMENT ON COLUMN AD_POLITICASCOMERCIAIS.ESCOPO_ESTADOS IS 'UFs onde a política se aplica, separadas por vírgula.';
COMMENT ON COLUMN AD_POLITICASCOMERCIAIS.SEG_CLIENTES_MANUAL IS 'Lista de CODPARC de clientes específicos onde a política se aplica.';
COMMENT ON COLUMN AD_POLITICASCOMERCIAIS.RESULT_NUTAB IS 'Número único da tabela de preços a ser aplicada se as condições forem atendidas.';
COMMENT ON COLUMN AD_POLITICASCOMERCIAIS.RESULT_PERCDESCONTO_MAX IS 'Percentual máximo de desconto que pode ser aplicado.';
COMMENT ON COLUMN AD_POLITICASCOMERCIAIS.RESULT_PERCACIMA_MAX IS 'Percentual máximo de acréscimo (overprice) que pode ser aplicado.';

-- Exemplo de inserção (apenas para referência)
/*
INSERT INTO AD_POLITICASCOMERCIAIS (
    ID_EMPRESA, NOME_POLITICA, ATIVO, PRIORIDADE, ESCOPO_ESTADOS, SEG_PERFIS_CLIENTE, RESULT_NUTAB, RESULT_PERCDESCONTO_MAX
) VALUES (
    1, 'Política de Varejo - SP', 'S', 1, 'SP', 'Varejo', 10, 5.00
);
*/
