
import { NextRequest, NextResponse } from 'next/server'
import { oracleService } from '@/lib/oracle-db'

export async function GET(request: NextRequest) {
    try {
        const connection = await oracleService.getConnection()

        // 1. Criar tabela AD_EQUIPES se não existir
        try {
            await connection.execute(`
        CREATE TABLE AD_EQUIPES (
          CODEQUIPE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          ID_EMPRESA NUMBER NOT NULL,
          NOME VARCHAR2(200 CHAR) NOT NULL,
          DESCRICAO VARCHAR2(500 CHAR),
          CODUSUARIO_GESTOR NUMBER,
          ATIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL,
          DATA_CRIACAO DATE DEFAULT SYSDATE NOT NULL,
          DATA_ATUALIZACAO DATE DEFAULT SYSDATE NOT NULL
        )
      `)
            console.log('✅ Tabela AD_EQUIPES criada')
        } catch (e: any) {
            if (e.message.includes('ORA-00955')) {
                console.log('ℹ️ Tabela AD_EQUIPES já existe')
            } else {
                throw e
            }
        }

        // 2. Criar tabela AD_EQUIPES_MEMBROS se não existir
        try {
            await connection.execute(`
        CREATE TABLE AD_EQUIPES_MEMBROS (
          CODMEMBRO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          CODEQUIPE NUMBER NOT NULL,
          CODUSUARIO NUMBER NOT NULL,
          ID_EMPRESA NUMBER NOT NULL,
          DATA_ENTRADA DATE DEFAULT SYSDATE NOT NULL,
          ATIVO CHAR(1 CHAR) DEFAULT 'S' NOT NULL,
          CONSTRAINT FK_EQUIPE_MEMBRO FOREIGN KEY (CODEQUIPE) REFERENCES AD_EQUIPES(CODEQUIPE)
        )
      `)
            console.log('✅ Tabela AD_EQUIPES_MEMBROS criada')
        } catch (e: any) {
            if (e.message.includes('ORA-00955')) {
                console.log('ℹ️ Tabela AD_EQUIPES_MEMBROS já existe')
            } else {
                throw e
            }
        }

        // 3. Atualizar tabela AD_POLITICASCOMERCIAIS para incluir ESCOPO_EMPRESAS
        try {
            await connection.execute(`
                ALTER TABLE AD_POLITICASCOMERCIAIS ADD (ESCOPO_EMPRESAS VARCHAR2(4000) CHAR)
            `)
            console.log('✅ Coluna ESCOPO_EMPRESAS adicionada em AD_POLITICASCOMERCIAIS')
        } catch (e: any) {
            if (e.message.includes('ORA-01430')) { // ORA-01430: column being added already exists in table
                console.log('ℹ️ Coluna ESCOPO_EMPRESAS já existe')
            } else {
                console.error('⚠️ Erro ao adicionar coluna ESCOPO_EMPRESAS (pode não ser crítico se tabela não existir ainda):', e.message)
            }
        }



        // 4. Atualizar tabela AD_POLITICASCOMERCIAIS para incluir ESCOPO_BAIRROS
        try {
            await connection.execute(`
                ALTER TABLE AD_POLITICASCOMERCIAIS ADD ESCOPO_BAIRROS VARCHAR2(4000)
            `)
            console.log('✅ Coluna ESCOPO_BAIRROS adicionada em AD_POLITICASCOMERCIAIS')
        } catch (e: any) {
            if (e.message.includes('ORA-01430')) { // ORA-01430: column being added already exists in table
                console.log('ℹ️ Coluna ESCOPO_BAIRROS já existe')
            } else {
                console.error('⚠️ Erro ao adicionar coluna ESCOPO_BAIRROS:', e.message)
            }
        }

        // 5. Update RESULT_NUTAB to VARCHAR2(4000) for multi-select support
        try {
            await connection.execute(`
                ALTER TABLE AD_POLITICASCOMERCIAIS MODIFY (RESULT_NUTAB VARCHAR2(4000) CHAR)
            `)
            console.log('✅ Coluna RESULT_NUTAB alterada para VARCHAR2(4000)')
        } catch (e: any) {
            // Ignore if already varchar or suitable
            console.log('ℹ️ Nota sobre RESULT_NUTAB:', e.message)
        }

        await connection.close()

        return NextResponse.json({ success: true, message: 'Tabelas verificadas/criadas com sucesso' })
    } catch (error: any) {
        console.error('Erro ao configurar banco:', error)
        return NextResponse.json({ success: false, error: error.message }, { status: 500 })
    }
}
